// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asnfpyzqccxzcyysdwfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbmZweXpxY2N4emN5eXNkd2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjYyNzQsImV4cCI6MjA2MjIwMjI3NH0.uic7ppU3F8aYLlg1p3YBkGlQYk7xcEDeqXW9UhOdfwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);